name: rich_clipboard
description: Flutter plugin for accessing rich text and other data types in the system clipboard.
homepage: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard
repository: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard
version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  rich_clipboard_macos: ^1.0.0
  rich_clipboard_windows: ^1.0.0
  rich_clipboard_linux: ^1.0.0
  rich_clipboard_web: ^1.0.0
  rich_clipboard_android:
    path: ../rich_clipboard_android
  rich_clipboard_ios: ^1.0.0
  rich_clipboard_platform_interface: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        default_package: rich_clipboard_macos
      windows:
        default_package: rich_clipboard_windows
      linux:
        default_package: rich_clipboard_linux
      web:
        default_package: rich_clipboard_web
      android:
        default_package: rich_clipboard_android
      ios:
        default_package: rich_clipboard_ios
