name: rich_clipboard_ios
description: iOS implementation of the rich_clipboard plugin
homepage: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_ios
repository: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_ios
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rich_clipboard_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: rich_clipboard
    platforms:
      ios:
        pluginClass: RichClipboardPlugin
        dartPluginClass: MethodChannelRichClipboard