name: rich_clipboard_android
description: Android implementation of the rich_clipboard plugin
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rich_clipboard_platform_interface: ^1.0.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: rich_clipboard
    platforms:
      android:
        package: com.bringingfire.rich_clipboard
        pluginClass: RichClipboardPlugin
        dartPluginClass: MethodChannelRichClipboard
