name: rich_clipboard_windows
description: Windows implementation of the rich_clipboard plugin.
homepage: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_windows
repository: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_windows
version: 1.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.15.0
  ffi: ">=1.1.2 <3.0.0"
  flutter:
    sdk: flutter
  rich_clipboard_platform_interface: ^1.0.0
  win32: ">=5.0.0"

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  plugin:
    implements: rich_clipboard
    platforms:
      windows:
        dartPluginClass: RichClipboardWindows
        pluginClass: none
