name: rich_clipboard_web
description: Web implementation of the rich_clipboard plugin.
homepage: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_web
repository: https://github.com/BringingFire/rich_clipboard/tree/dev/rich_clipboard_web
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4
  rich_clipboard_platform_interface: ^0.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: rich_clipboard
    platforms:
      web:
        pluginClass: RichClipboardWeb
        fileName: rich_clipboard_web.dart
